[cmake]
version = "3.15"
arguments = [
    "CMAKE_SIZEOF_VOID_P=8",
    "ZYDIS_BUILD_TOOLS=OFF",
    "ZYDIS_BUILD_EXAMPLES=OFF"
]

[project]
name = "vmpfix"

cmake-before = """
add_subdirectory(Blackbone/src)
if(CMAKE_SIZEOF_VOID_P EQUAL 8)
    link_directories(Blackbone/src/3rd_party/DIA/lib/amd64)
elseif(CMAKE_SIZEOF_VOID_P EQUAL 4)
    link_directories(Blackbone/src/3rd_party/DIA/lib)
endif()
"""

# [find-package]

[fetch-content]
argparse = { git = "https://github.com/p-ranav/argparse.git" }
linux-pe = { git = "https://github.com/can1357/linux-pe.git" }
# https://github.com/zyantific/zydis/releases/tag/v3.2.1"
Zydis    = { git = "https://github.com/zyantific/zydis.git", tag = "875c8a75344d0ad71b02bcd2cc5e3acb87e7b003" }

[target.vmpfix]
type = "executable"
sources = [
    "src/*.cpp", 
    "include/*.hpp"
]
include-directories = [
    "include",
    "Blackbone/src",
]

compile-features = ["cxx_std_20"]

link-libraries = [
    "BlackBone",
    "diaguids",
    "linux-pe",
    "Zydis",
    "argparse"
]
